# Gradle properties
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod properties
mod_group=dev.nickrobson.minecraft
mod_id=skillmmo
mod_version=0.1.13
mod_name=SkillMMO
mod_description=Adds experience-based skills that blocks, items, and more are gated behind

# Build dependency versions
loom_version=1.17-SNAPSHOT
fabric_loader_version=0.19.3
minecraft_version=26.1.2
fabric_api_version=0.152.1+26.1.2
badpackets_version=0.12.2
clothconfig_version=26.1.154
libgui_version=16.0.1+26.1
wthit_version=19.0.1

# Dependency ranges
java_version_range=>=25
minecraft_version_range=>=26.1 <=26.1.2
fabric_loader_version_range=>=0.19.3
fabric_api_version_range=*
cloth_config_version_range=*
wthit_version_range=*
