# Gradle properties
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod properties
mod_group=dev.nickrobson.minecraft
mod_id=skillmmo
mod_version=0.1.11
mod_name=SkillMMO
mod_description=Adds experience-based skills that blocks, items, and more are gated behind

# Build dependency versions
minecraft_version=1.20.4
yarn_mappings_version=1.20.4+build.3
fabric_loader_version=0.16.14
fabric_api_version=0.97.3+1.20.4
badpackets_version=0.6.2
clothconfig_version=13.0.138
libgui_version=9.2.2+1.20.2
wthit_version=10.9.4

# Dependency ranges
java_version_range=>=17
minecraft_version_range=>=1.20.4 <=1.20.4
fabric_loader_version_range=>=0.16.14
fabric_api_version_range=*
cloth_config_version_range=^13.0.0
wthit_version_range=^10.9.0
