# Gradle properties
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod properties
mod_group=dev.nickrobson.minecraft
mod_id=skillmmo
mod_version=0.1.12
mod_name=SkillMMO
mod_description=Adds experience-based skills that blocks, items, and more are gated behind

# Build dependency versions
loom_version=1.11-SNAPSHOT
fabric_loader_version=0.16.14
minecraft_version=1.21.4
yarn_mappings_version=1.21.4+build.8
fabric_api_version=0.119.4+1.21.4
badpackets_version=0.8.2
clothconfig_version=17.0.144
libgui_version=12.0.1+1.21.2
wthit_version=14.1.7

# Dependency ranges
java_version_range=>=21
minecraft_version_range=>=1.21.4 <=1.21.4
fabric_loader_version_range=>=0.16.14
fabric_api_version_range=*
cloth_config_version_range=*
wthit_version_range=*
