modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="MIT"

[properties]
# ${mod_name} is not actually a NeoForge mod,
# it's a Fabric mod that you can run on NeoForge using Connector
"connector:placeholder"=true

[[mods]]
modId="${mod_id}"
displayName="${mod_name}"
version="${mod_version}"
authors="Nick Robson"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="connector"
mandatory=true
versionRange="${connector_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cloth_config"
mandatory=true
versionRange="${cloth_config_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="wthit"
mandatory=false
versionRange="${wthit_version_range}"
ordering="NONE"
side="BOTH"
